DEVICE_ID = "esp32_c3_gift_display"
RUN_MODE = "display_only"
UPLOAD_ENABLED = False

WIFI_SSID = ""
WIFI_PASSWORD = ""
SERVER_URL = ""
TEMP_WINDOWS_SERVER_URL = ""

DISPLAY_REFRESH_SECONDS = 2
UPLOAD_INTERVAL_SECONDS = 60
RANGE_TEST_INTERVAL_SECONDS = 10
COMPONENT_TEST_INTERVAL_SECONDS = 10
WIFI_TIMEOUT_SECONDS = 15
HTTP_TIMEOUT_SECONDS = 10
MAX_PENDING_UPLOADS = 1

DHT_PIN = 4
I2C_BUS_ID = 0
I2C_SCL_PIN = 9
I2C_SDA_PIN = 8

BH1750_ADDR = 0x23
OLED_ENABLED = True
OLED_LAYOUT = "data_only"
OLED_SHOW_MODE = True
OLED_MODE_LABEL = "DISPLAY ONLY"
OLED_ADDR = 0x3C
OLED_WIDTH = 128
OLED_HEIGHT = 64
