DEVICE_ID = "outdoor"
RUN_MODE = "summer"

WIFI_SSID = "YOUR_WIFI_SSID"
WIFI_PASSWORD = "YOUR_WIFI_PASSWORD"
SERVER_URL = "http://YOUR-PC-IP:8000/api/v1/readings"
TEMP_WINDOWS_SERVER_URL = None

UPLOAD_INTERVAL_SECONDS = 60
RANGE_TEST_INTERVAL_SECONDS = 10
COMPONENT_TEST_INTERVAL_SECONDS = 10
WIFI_TIMEOUT_SECONDS = 15
HTTP_TIMEOUT_SECONDS = 10
MAX_PENDING_UPLOADS = 8

DHT_PIN = 4
I2C_BUS_ID = 0
I2C_SCL_PIN = 22
I2C_SDA_PIN = 21

BH1750_ADDR = 0x23
OLED_ENABLED = False
OLED_ADDR = 0x3C
OLED_WIDTH = 128
OLED_HEIGHT = 64
